/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QFrame *frameTopStatus;
    QLabel *lblComPort;
    QToolButton *Button_SelCOM;
    QLabel *lblConnectStatusTitle;
    QLabel *lblConnectStatus;
    QLabel *lblCurrentRangeTitle;
    QLabel *lblCurrentRange;
    QLabel *lblVoltageRangeTitle;
    QLabel *lblVoltageRange;
    QLabel *lblMeasureModeTitle;
    QLabel *lblMeasureMode;
    QLabel *lblMeasureStateTitle;
    QLabel *lblMeasureState;
    QFrame *frameSideNav;
    QLabel *lblNavTitle;
    QPushButton *btnPageExperiment;
    QPushButton *btnPageSample;
    QPushButton *btnPageResult;
    QPushButton *btnPageDebug;
    QStackedWidget *stackedWidgetMain;
    QWidget *pageExperiment;
    QGroupBox *grpExperimentControl;
    QLabel *lblModeSelect;
    QToolButton *ToolButton_MeasureMode;
    QLabel *lblCurrentRangeSelect;
    QToolButton *Button_CurrPos;
    QLabel *lblVoltageRangeSelect;
    QToolButton *Button_VolRange;
    QPushButton *Button_MeasStart;
    QPushButton *btnStopMeasure;
    QPushButton *btnClearCurrentData;
    QGroupBox *grpRealtimeData;
    QLabel *Label_NameDataVoltage;
    QLabel *Label_VoltData;
    QLabel *Label_NameDataCurrent;
    QLabel *Label_CurrData;
    QLabel *lblResistanceTitle;
    QLabel *lblRealtimeResistance;
    QLabel *Label_NameDataResistivity;
    QLabel *Label_ResData;
    QGroupBox *grpMeasureProgress;
    QLabel *lblStageTitle;
    QLabel *Label_MeasureProgress;
    QProgressBar *ProgressBar_MeasureProgress;
    QLabel *lblStageHint;
    QWidget *pageSample;
    QGroupBox *grpSampleBasic;
    QLabel *Label_Name_SemiType;
    QPushButton *Button_SelSemiType;
    QLabel *Label_Name_Temperature;
    QLineEdit *cin_Temperature;
    QLabel *Label_Name_Temperature_2;
    QLabel *Label_Name_SampleThickness;
    QLineEdit *cin_Thickness;
    QLabel *Label_Name_SampleThickness_2;
    QLabel *Label_Name_SampleDiameter;
    QLineEdit *cin_SampleDiameter;
    QLabel *Label_Name_SampleDiameter_2;
    QLabel *Label_Name_SampleDiameter_3;
    QLineEdit *cin_ProbeSpacing;
    QLabel *Label_Name_SampleDiameter_4;
    QLabel *Label_Name_FspCorrectionFactor;
    QLineEdit *cin_FspCorrectionFactor;
    QLabel *Label_Name_Temperature_3;
    QLineEdit *cin_a;
    QLabel *Label_Name_Temperature_4;
    QLineEdit *cin_b;
    QGroupBox *grpCorrectionFactor;
    QLabel *lblWsTitle;
    QLabel *lblWS;
    QLabel *lblSdTitle;
    QLabel *lblSD;
    QLabel *lblGeometryFactorTitle;
    QLabel *lblGeometryFactor;
    QLabel *lblTemperatureFactorTitle;
    QLabel *lblTemperatureFactor;
    QLabel *lblTotalFactorTitle;
    QLabel *lblTotalFactor;
    QGroupBox *grpSampleActions;
    QLabel *Label_Name_SampleDiameter_5;
    QLineEdit *cin_CurrErrorBound;
    QLabel *Label_Name_SampleDiameter_6;
    QPushButton *btnSaveParams;
    QPushButton *btnResetParams;
    QPushButton *btnImportParams;
    QPushButton *btnExportParams;
    QProgressBar *ProgressBar_Init;
    QPushButton *Button_Temperature;
    QPushButton *Button_Thickness;
    QPushButton *Button_SampleDiameter;
    QPushButton *Button_ProbeSpacing;
    QPushButton *Button_FspCorrectionFactor;
    QPushButton *Button_ab;
    QPushButton *Button_CurrErrorBound;
    QWidget *pageResult;
    QGroupBox *grpForwardData;
    QTableWidget *TableWidget_f;
    QGroupBox *grpReverseData;
    QTableWidget *TableWidget_r;
    QGroupBox *grpStatistics;
    QLabel *lblAverageTitle;
    QLabel *lblAverageValue;
    QLabel *lblStdTitle;
    QLabel *lblStdValue;
    QLabel *lblFinalResistivityTitle;
    QLabel *lblFinalResistivity;
    QGroupBox *grpFileInfo;
    QLabel *lblMeasureStartTimeTitle;
    QLabel *lblMeasureStartTime;
    QLabel *lblDataPathTitle;
    QLabel *lblDataSavePath;
    QPushButton *btnOpenDataFolder;
    QGroupBox *grpResultActions;
    QPushButton *btnExportCsv;
    QPushButton *btnExportExcel;
    QPushButton *btnCopyFinalResult;
    QPushButton *btnClearResult;
    QWidget *pageDebug;
    QGroupBox *grpPidDebug;
    QLabel *Label_Name_Kp;
    QLineEdit *cin_Kp;
    QLabel *Label_Name_Ti;
    QLineEdit *cin_Ti;
    QLabel *Label_Name_Td;
    QLineEdit *cin_Td;
    QToolButton *ToolButton_ControlAlgo;
    QGroupBox *grpVoltageDebug;
    QLabel *lblControlVoltageDebugTitle;
    QLineEdit *cin_ControlVoltage;
    QPushButton *Button_SendControlVoltage;
    QPushButton *Button_ControlVoltage;
    QGroupBox *grpManualCommand;
    QPushButton *Button_SendCurrentPosition;
    QPushButton *Button_SendVoltageRange;
    QPushButton *pushButton_3;
    QGroupBox *grpCurrentReadDebug;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *Label_Name_Current;
    QLabel *Label_Current;
    QGroupBox *grpPidState;
    QLabel *lblPidSpTitle;
    QLabel *lblPidSp;
    QLabel *lblPidPvTitle;
    QLabel *lblPidPv;
    QLabel *lblPidErrTitle;
    QLabel *lblPidErr;
    QLabel *lblPidUkTitle;
    QLabel *lblPidUk;
    QLabel *lblPidLastUkTitle;
    QLabel *lblPidLastUk;
    QLabel *Label_Name_Current_2;
    QLabel *Label_RE_Current;
    QGroupBox *grpCommDebug;
    QTextEdit *logText_1;
    QPushButton *Button_logText1_CLR;
    QLabel *lblAckNackTitle;
    QLabel *lblAckNack;
    QLabel *lblOperationDoneTitle;
    QLabel *lblOperationDone;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName(QStringLiteral("Widget"));
        Widget->resize(1200, 760);
        Widget->setMinimumSize(QSize(1200, 760));
        Widget->setMaximumSize(QSize(1200, 760));
        Widget->setStyleSheet(QLatin1String("QWidget { font-family: \"Microsoft YaHei\", \"SimSun\"; font-size: 10pt; }\n"
"QFrame#frameTopStatus, QFrame#frameSideNav { border: 1px solid #b9b9b9; border-radius: 2px; background-color: #f5f5f5; }\n"
"QGroupBox { font-weight: 600; margin-top: 8px; padding-top: 12px; }\n"
"QGroupBox::title { subcontrol-origin: margin; left: 10px; padding: 0 4px; }\n"
"QPushButton, QToolButton { min-height: 24px; padding: 3px 10px; }\n"
"QLineEdit { min-height: 22px; padding: 2px 4px; }\n"
"QTableWidget, QTextEdit { background-color: white; }\n"
"QLabel#Label_VoltData, QLabel#Label_CurrData, QLabel#lblRealtimeResistance, QLabel#Label_ResData, QLabel#Label_MeasureProgress, QLabel#Label_Current, QLabel#lblAverageValue, QLabel#lblStdValue, QLabel#lblFinalResistivity, QLabel#lblWS, QLabel#lblSD, QLabel#lblGeometryFactor, QLabel#lblTemperatureFactor, QLabel#lblTotalFactor { font-family: \"Consolas\"; font-size: 13pt; font-weight: 600; }\n"
"QLabel#lblConnectStatus, QLabel#lblCurrentRange, QLabel#lblVoltageRange, QLabel#lblMeasureM"
                        "ode, QLabel#lblMeasureState { font-weight: 600; }\n"
"QLabel#lblNavTitle { font-weight: 600; }\n"
"QPushButton#Button_MeasStart { font-weight: 600; min-height: 30px; }"));
        frameTopStatus = new QFrame(Widget);
        frameTopStatus->setObjectName(QStringLiteral("frameTopStatus"));
        frameTopStatus->setGeometry(QRect(20, 10, 1160, 70));
        frameTopStatus->setFrameShape(QFrame::StyledPanel);
        lblComPort = new QLabel(frameTopStatus);
        lblComPort->setObjectName(QStringLiteral("lblComPort"));
        lblComPort->setGeometry(QRect(20, 21, 50, 28));
        lblComPort->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Button_SelCOM = new QToolButton(frameTopStatus);
        Button_SelCOM->setObjectName(QStringLiteral("Button_SelCOM"));
        Button_SelCOM->setGeometry(QRect(72, 18, 120, 32));
        lblConnectStatusTitle = new QLabel(frameTopStatus);
        lblConnectStatusTitle->setObjectName(QStringLiteral("lblConnectStatusTitle"));
        lblConnectStatusTitle->setGeometry(QRect(215, 21, 70, 28));
        lblConnectStatusTitle->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblConnectStatus = new QLabel(frameTopStatus);
        lblConnectStatus->setObjectName(QStringLiteral("lblConnectStatus"));
        lblConnectStatus->setGeometry(QRect(285, 18, 90, 32));
        lblConnectStatus->setAlignment(Qt::AlignCenter);
        lblCurrentRangeTitle = new QLabel(frameTopStatus);
        lblCurrentRangeTitle->setObjectName(QStringLiteral("lblCurrentRangeTitle"));
        lblCurrentRangeTitle->setGeometry(QRect(400, 21, 80, 28));
        lblCurrentRangeTitle->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblCurrentRange = new QLabel(frameTopStatus);
        lblCurrentRange->setObjectName(QStringLiteral("lblCurrentRange"));
        lblCurrentRange->setGeometry(QRect(480, 18, 90, 32));
        lblCurrentRange->setAlignment(Qt::AlignCenter);
        lblVoltageRangeTitle = new QLabel(frameTopStatus);
        lblVoltageRangeTitle->setObjectName(QStringLiteral("lblVoltageRangeTitle"));
        lblVoltageRangeTitle->setGeometry(QRect(595, 21, 80, 28));
        lblVoltageRangeTitle->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVoltageRange = new QLabel(frameTopStatus);
        lblVoltageRange->setObjectName(QStringLiteral("lblVoltageRange"));
        lblVoltageRange->setGeometry(QRect(675, 18, 90, 32));
        lblVoltageRange->setAlignment(Qt::AlignCenter);
        lblMeasureModeTitle = new QLabel(frameTopStatus);
        lblMeasureModeTitle->setObjectName(QStringLiteral("lblMeasureModeTitle"));
        lblMeasureModeTitle->setGeometry(QRect(790, 21, 80, 28));
        lblMeasureModeTitle->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblMeasureMode = new QLabel(frameTopStatus);
        lblMeasureMode->setObjectName(QStringLiteral("lblMeasureMode"));
        lblMeasureMode->setGeometry(QRect(870, 18, 140, 32));
        lblMeasureMode->setAlignment(Qt::AlignCenter);
        lblMeasureStateTitle = new QLabel(frameTopStatus);
        lblMeasureStateTitle->setObjectName(QStringLiteral("lblMeasureStateTitle"));
        lblMeasureStateTitle->setGeometry(QRect(1025, 21, 45, 28));
        lblMeasureStateTitle->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblMeasureState = new QLabel(frameTopStatus);
        lblMeasureState->setObjectName(QStringLiteral("lblMeasureState"));
        lblMeasureState->setGeometry(QRect(1070, 18, 80, 32));
        lblMeasureState->setAlignment(Qt::AlignCenter);
        frameSideNav = new QFrame(Widget);
        frameSideNav->setObjectName(QStringLiteral("frameSideNav"));
        frameSideNav->setGeometry(QRect(20, 90, 1160, 58));
        frameSideNav->setFrameShape(QFrame::StyledPanel);
        lblNavTitle = new QLabel(frameSideNav);
        lblNavTitle->setObjectName(QStringLiteral("lblNavTitle"));
        lblNavTitle->setGeometry(QRect(20, 14, 90, 30));
        lblNavTitle->setAlignment(Qt::AlignCenter);
        btnPageExperiment = new QPushButton(frameSideNav);
        btnPageExperiment->setObjectName(QStringLiteral("btnPageExperiment"));
        btnPageExperiment->setGeometry(QRect(130, 12, 150, 34));
        btnPageSample = new QPushButton(frameSideNav);
        btnPageSample->setObjectName(QStringLiteral("btnPageSample"));
        btnPageSample->setGeometry(QRect(295, 12, 150, 34));
        btnPageResult = new QPushButton(frameSideNav);
        btnPageResult->setObjectName(QStringLiteral("btnPageResult"));
        btnPageResult->setGeometry(QRect(460, 12, 150, 34));
        btnPageDebug = new QPushButton(frameSideNav);
        btnPageDebug->setObjectName(QStringLiteral("btnPageDebug"));
        btnPageDebug->setGeometry(QRect(1000, 12, 140, 34));
        stackedWidgetMain = new QStackedWidget(Widget);
        stackedWidgetMain->setObjectName(QStringLiteral("stackedWidgetMain"));
        stackedWidgetMain->setGeometry(QRect(20, 160, 1160, 580));
        pageExperiment = new QWidget();
        pageExperiment->setObjectName(QStringLiteral("pageExperiment"));
        pageExperiment->setGeometry(QRect(0, 0, 1160, 580));
        grpExperimentControl = new QGroupBox(pageExperiment);
        grpExperimentControl->setObjectName(QStringLiteral("grpExperimentControl"));
        grpExperimentControl->setGeometry(QRect(20, 10, 1120, 130));
        lblModeSelect = new QLabel(grpExperimentControl);
        lblModeSelect->setObjectName(QStringLiteral("lblModeSelect"));
        lblModeSelect->setGeometry(QRect(25, 34, 80, 28));
        ToolButton_MeasureMode = new QToolButton(grpExperimentControl);
        ToolButton_MeasureMode->setObjectName(QStringLiteral("ToolButton_MeasureMode"));
        ToolButton_MeasureMode->setGeometry(QRect(115, 30, 180, 32));
        lblCurrentRangeSelect = new QLabel(grpExperimentControl);
        lblCurrentRangeSelect->setObjectName(QStringLiteral("lblCurrentRangeSelect"));
        lblCurrentRangeSelect->setGeometry(QRect(330, 34, 80, 28));
        Button_CurrPos = new QToolButton(grpExperimentControl);
        Button_CurrPos->setObjectName(QStringLiteral("Button_CurrPos"));
        Button_CurrPos->setGeometry(QRect(420, 30, 150, 32));
        lblVoltageRangeSelect = new QLabel(grpExperimentControl);
        lblVoltageRangeSelect->setObjectName(QStringLiteral("lblVoltageRangeSelect"));
        lblVoltageRangeSelect->setGeometry(QRect(600, 34, 80, 28));
        Button_VolRange = new QToolButton(grpExperimentControl);
        Button_VolRange->setObjectName(QStringLiteral("Button_VolRange"));
        Button_VolRange->setGeometry(QRect(690, 30, 150, 32));
        Button_MeasStart = new QPushButton(grpExperimentControl);
        Button_MeasStart->setObjectName(QStringLiteral("Button_MeasStart"));
        Button_MeasStart->setGeometry(QRect(25, 80, 150, 36));
        btnStopMeasure = new QPushButton(grpExperimentControl);
        btnStopMeasure->setObjectName(QStringLiteral("btnStopMeasure"));
        btnStopMeasure->setGeometry(QRect(195, 80, 150, 36));
        btnClearCurrentData = new QPushButton(grpExperimentControl);
        btnClearCurrentData->setObjectName(QStringLiteral("btnClearCurrentData"));
        btnClearCurrentData->setGeometry(QRect(365, 80, 150, 36));
        grpRealtimeData = new QGroupBox(pageExperiment);
        grpRealtimeData->setObjectName(QStringLiteral("grpRealtimeData"));
        grpRealtimeData->setGeometry(QRect(20, 155, 540, 250));
        Label_NameDataVoltage = new QLabel(grpRealtimeData);
        Label_NameDataVoltage->setObjectName(QStringLiteral("Label_NameDataVoltage"));
        Label_NameDataVoltage->setGeometry(QRect(35, 40, 120, 30));
        Label_VoltData = new QLabel(grpRealtimeData);
        Label_VoltData->setObjectName(QStringLiteral("Label_VoltData"));
        Label_VoltData->setGeometry(QRect(185, 40, 300, 30));
        Label_NameDataCurrent = new QLabel(grpRealtimeData);
        Label_NameDataCurrent->setObjectName(QStringLiteral("Label_NameDataCurrent"));
        Label_NameDataCurrent->setGeometry(QRect(35, 90, 120, 30));
        Label_CurrData = new QLabel(grpRealtimeData);
        Label_CurrData->setObjectName(QStringLiteral("Label_CurrData"));
        Label_CurrData->setGeometry(QRect(185, 90, 300, 30));
        lblResistanceTitle = new QLabel(grpRealtimeData);
        lblResistanceTitle->setObjectName(QStringLiteral("lblResistanceTitle"));
        lblResistanceTitle->setGeometry(QRect(35, 140, 120, 30));
        lblRealtimeResistance = new QLabel(grpRealtimeData);
        lblRealtimeResistance->setObjectName(QStringLiteral("lblRealtimeResistance"));
        lblRealtimeResistance->setGeometry(QRect(185, 140, 300, 30));
        Label_NameDataResistivity = new QLabel(grpRealtimeData);
        Label_NameDataResistivity->setObjectName(QStringLiteral("Label_NameDataResistivity"));
        Label_NameDataResistivity->setGeometry(QRect(35, 190, 120, 30));
        Label_ResData = new QLabel(grpRealtimeData);
        Label_ResData->setObjectName(QStringLiteral("Label_ResData"));
        Label_ResData->setGeometry(QRect(185, 190, 300, 30));
        grpMeasureProgress = new QGroupBox(pageExperiment);
        grpMeasureProgress->setObjectName(QStringLiteral("grpMeasureProgress"));
        grpMeasureProgress->setGeometry(QRect(580, 155, 560, 250));
        lblStageTitle = new QLabel(grpMeasureProgress);
        lblStageTitle->setObjectName(QStringLiteral("lblStageTitle"));
        lblStageTitle->setGeometry(QRect(35, 45, 100, 30));
        Label_MeasureProgress = new QLabel(grpMeasureProgress);
        Label_MeasureProgress->setObjectName(QStringLiteral("Label_MeasureProgress"));
        Label_MeasureProgress->setGeometry(QRect(150, 45, 360, 30));
        ProgressBar_MeasureProgress = new QProgressBar(grpMeasureProgress);
        ProgressBar_MeasureProgress->setObjectName(QStringLiteral("ProgressBar_MeasureProgress"));
        ProgressBar_MeasureProgress->setGeometry(QRect(35, 110, 470, 30));
        ProgressBar_MeasureProgress->setValue(0);
        lblStageHint = new QLabel(grpMeasureProgress);
        lblStageHint->setObjectName(QStringLiteral("lblStageHint"));
        lblStageHint->setGeometry(QRect(35, 165, 470, 50));
        lblStageHint->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        stackedWidgetMain->addWidget(pageExperiment);
        pageSample = new QWidget();
        pageSample->setObjectName(QStringLiteral("pageSample"));
        pageSample->setGeometry(QRect(0, 0, 1160, 580));
        grpSampleBasic = new QGroupBox(pageSample);
        grpSampleBasic->setObjectName(QStringLiteral("grpSampleBasic"));
        grpSampleBasic->setGeometry(QRect(20, 10, 540, 430));
        Label_Name_SemiType = new QLabel(grpSampleBasic);
        Label_Name_SemiType->setObjectName(QStringLiteral("Label_Name_SemiType"));
        Label_Name_SemiType->setGeometry(QRect(30, 35, 110, 30));
        Button_SelSemiType = new QPushButton(grpSampleBasic);
        Button_SelSemiType->setObjectName(QStringLiteral("Button_SelSemiType"));
        Button_SelSemiType->setGeometry(QRect(160, 32, 110, 34));
        Label_Name_Temperature = new QLabel(grpSampleBasic);
        Label_Name_Temperature->setObjectName(QStringLiteral("Label_Name_Temperature"));
        Label_Name_Temperature->setGeometry(QRect(30, 85, 110, 30));
        cin_Temperature = new QLineEdit(grpSampleBasic);
        cin_Temperature->setObjectName(QStringLiteral("cin_Temperature"));
        cin_Temperature->setGeometry(QRect(160, 85, 150, 30));
        Label_Name_Temperature_2 = new QLabel(grpSampleBasic);
        Label_Name_Temperature_2->setObjectName(QStringLiteral("Label_Name_Temperature_2"));
        Label_Name_Temperature_2->setGeometry(QRect(325, 85, 40, 30));
        Label_Name_SampleThickness = new QLabel(grpSampleBasic);
        Label_Name_SampleThickness->setObjectName(QStringLiteral("Label_Name_SampleThickness"));
        Label_Name_SampleThickness->setGeometry(QRect(30, 135, 110, 30));
        cin_Thickness = new QLineEdit(grpSampleBasic);
        cin_Thickness->setObjectName(QStringLiteral("cin_Thickness"));
        cin_Thickness->setGeometry(QRect(160, 135, 150, 30));
        Label_Name_SampleThickness_2 = new QLabel(grpSampleBasic);
        Label_Name_SampleThickness_2->setObjectName(QStringLiteral("Label_Name_SampleThickness_2"));
        Label_Name_SampleThickness_2->setGeometry(QRect(325, 135, 40, 30));
        Label_Name_SampleDiameter = new QLabel(grpSampleBasic);
        Label_Name_SampleDiameter->setObjectName(QStringLiteral("Label_Name_SampleDiameter"));
        Label_Name_SampleDiameter->setGeometry(QRect(30, 185, 110, 30));
        cin_SampleDiameter = new QLineEdit(grpSampleBasic);
        cin_SampleDiameter->setObjectName(QStringLiteral("cin_SampleDiameter"));
        cin_SampleDiameter->setGeometry(QRect(160, 185, 150, 30));
        Label_Name_SampleDiameter_2 = new QLabel(grpSampleBasic);
        Label_Name_SampleDiameter_2->setObjectName(QStringLiteral("Label_Name_SampleDiameter_2"));
        Label_Name_SampleDiameter_2->setGeometry(QRect(325, 185, 40, 30));
        Label_Name_SampleDiameter_3 = new QLabel(grpSampleBasic);
        Label_Name_SampleDiameter_3->setObjectName(QStringLiteral("Label_Name_SampleDiameter_3"));
        Label_Name_SampleDiameter_3->setGeometry(QRect(30, 235, 110, 30));
        cin_ProbeSpacing = new QLineEdit(grpSampleBasic);
        cin_ProbeSpacing->setObjectName(QStringLiteral("cin_ProbeSpacing"));
        cin_ProbeSpacing->setGeometry(QRect(160, 235, 150, 30));
        Label_Name_SampleDiameter_4 = new QLabel(grpSampleBasic);
        Label_Name_SampleDiameter_4->setObjectName(QStringLiteral("Label_Name_SampleDiameter_4"));
        Label_Name_SampleDiameter_4->setGeometry(QRect(325, 235, 40, 30));
        Label_Name_FspCorrectionFactor = new QLabel(grpSampleBasic);
        Label_Name_FspCorrectionFactor->setObjectName(QStringLiteral("Label_Name_FspCorrectionFactor"));
        Label_Name_FspCorrectionFactor->setGeometry(QRect(30, 285, 120, 30));
        cin_FspCorrectionFactor = new QLineEdit(grpSampleBasic);
        cin_FspCorrectionFactor->setObjectName(QStringLiteral("cin_FspCorrectionFactor"));
        cin_FspCorrectionFactor->setGeometry(QRect(160, 285, 150, 30));
        Label_Name_Temperature_3 = new QLabel(grpSampleBasic);
        Label_Name_Temperature_3->setObjectName(QStringLiteral("Label_Name_Temperature_3"));
        Label_Name_Temperature_3->setGeometry(QRect(30, 335, 110, 30));
        cin_a = new QLineEdit(grpSampleBasic);
        cin_a->setObjectName(QStringLiteral("cin_a"));
        cin_a->setGeometry(QRect(160, 335, 150, 30));
        Label_Name_Temperature_4 = new QLabel(grpSampleBasic);
        Label_Name_Temperature_4->setObjectName(QStringLiteral("Label_Name_Temperature_4"));
        Label_Name_Temperature_4->setGeometry(QRect(30, 385, 110, 30));
        cin_b = new QLineEdit(grpSampleBasic);
        cin_b->setObjectName(QStringLiteral("cin_b"));
        cin_b->setGeometry(QRect(160, 385, 150, 30));
        grpCorrectionFactor = new QGroupBox(pageSample);
        grpCorrectionFactor->setObjectName(QStringLiteral("grpCorrectionFactor"));
        grpCorrectionFactor->setGeometry(QRect(580, 10, 560, 270));
        lblWsTitle = new QLabel(grpCorrectionFactor);
        lblWsTitle->setObjectName(QStringLiteral("lblWsTitle"));
        lblWsTitle->setGeometry(QRect(35, 45, 170, 28));
        lblWS = new QLabel(grpCorrectionFactor);
        lblWS->setObjectName(QStringLiteral("lblWS"));
        lblWS->setGeometry(QRect(230, 45, 260, 28));
        lblSdTitle = new QLabel(grpCorrectionFactor);
        lblSdTitle->setObjectName(QStringLiteral("lblSdTitle"));
        lblSdTitle->setGeometry(QRect(35, 85, 170, 28));
        lblSD = new QLabel(grpCorrectionFactor);
        lblSD->setObjectName(QStringLiteral("lblSD"));
        lblSD->setGeometry(QRect(230, 85, 260, 28));
        lblGeometryFactorTitle = new QLabel(grpCorrectionFactor);
        lblGeometryFactorTitle->setObjectName(QStringLiteral("lblGeometryFactorTitle"));
        lblGeometryFactorTitle->setGeometry(QRect(35, 125, 170, 28));
        lblGeometryFactor = new QLabel(grpCorrectionFactor);
        lblGeometryFactor->setObjectName(QStringLiteral("lblGeometryFactor"));
        lblGeometryFactor->setGeometry(QRect(230, 125, 260, 28));
        lblTemperatureFactorTitle = new QLabel(grpCorrectionFactor);
        lblTemperatureFactorTitle->setObjectName(QStringLiteral("lblTemperatureFactorTitle"));
        lblTemperatureFactorTitle->setGeometry(QRect(35, 165, 170, 28));
        lblTemperatureFactor = new QLabel(grpCorrectionFactor);
        lblTemperatureFactor->setObjectName(QStringLiteral("lblTemperatureFactor"));
        lblTemperatureFactor->setGeometry(QRect(230, 165, 260, 28));
        lblTotalFactorTitle = new QLabel(grpCorrectionFactor);
        lblTotalFactorTitle->setObjectName(QStringLiteral("lblTotalFactorTitle"));
        lblTotalFactorTitle->setGeometry(QRect(35, 205, 170, 28));
        lblTotalFactor = new QLabel(grpCorrectionFactor);
        lblTotalFactor->setObjectName(QStringLiteral("lblTotalFactor"));
        lblTotalFactor->setGeometry(QRect(230, 205, 260, 28));
        grpSampleActions = new QGroupBox(pageSample);
        grpSampleActions->setObjectName(QStringLiteral("grpSampleActions"));
        grpSampleActions->setGeometry(QRect(580, 300, 560, 150));
        Label_Name_SampleDiameter_5 = new QLabel(grpSampleActions);
        Label_Name_SampleDiameter_5->setObjectName(QStringLiteral("Label_Name_SampleDiameter_5"));
        Label_Name_SampleDiameter_5->setGeometry(QRect(30, 35, 110, 30));
        cin_CurrErrorBound = new QLineEdit(grpSampleActions);
        cin_CurrErrorBound->setObjectName(QStringLiteral("cin_CurrErrorBound"));
        cin_CurrErrorBound->setGeometry(QRect(160, 35, 160, 28));
        Label_Name_SampleDiameter_6 = new QLabel(grpSampleActions);
        Label_Name_SampleDiameter_6->setObjectName(QStringLiteral("Label_Name_SampleDiameter_6"));
        Label_Name_SampleDiameter_6->setGeometry(QRect(315, 35, 40, 30));
        btnSaveParams = new QPushButton(grpSampleActions);
        btnSaveParams->setObjectName(QStringLiteral("btnSaveParams"));
        btnSaveParams->setGeometry(QRect(30, 85, 120, 32));
        btnResetParams = new QPushButton(grpSampleActions);
        btnResetParams->setObjectName(QStringLiteral("btnResetParams"));
        btnResetParams->setGeometry(QRect(165, 85, 90, 32));
        btnImportParams = new QPushButton(grpSampleActions);
        btnImportParams->setObjectName(QStringLiteral("btnImportParams"));
        btnImportParams->setGeometry(QRect(270, 85, 90, 32));
        btnExportParams = new QPushButton(grpSampleActions);
        btnExportParams->setObjectName(QStringLiteral("btnExportParams"));
        btnExportParams->setGeometry(QRect(375, 85, 90, 32));
        ProgressBar_Init = new QProgressBar(grpSampleActions);
        ProgressBar_Init->setObjectName(QStringLiteral("ProgressBar_Init"));
        ProgressBar_Init->setGeometry(QRect(30, 122, 470, 22));
        ProgressBar_Init->setValue(0);
        Button_Temperature = new QPushButton(pageSample);
        Button_Temperature->setObjectName(QStringLiteral("Button_Temperature"));
        Button_Temperature->setGeometry(QRect(0, 0, 10, 10));
        Button_Temperature->setVisible(false);
        Button_Thickness = new QPushButton(pageSample);
        Button_Thickness->setObjectName(QStringLiteral("Button_Thickness"));
        Button_Thickness->setGeometry(QRect(0, 4, 10, 10));
        Button_Thickness->setVisible(false);
        Button_SampleDiameter = new QPushButton(pageSample);
        Button_SampleDiameter->setObjectName(QStringLiteral("Button_SampleDiameter"));
        Button_SampleDiameter->setGeometry(QRect(0, 8, 10, 10));
        Button_SampleDiameter->setVisible(false);
        Button_ProbeSpacing = new QPushButton(pageSample);
        Button_ProbeSpacing->setObjectName(QStringLiteral("Button_ProbeSpacing"));
        Button_ProbeSpacing->setGeometry(QRect(0, 12, 10, 10));
        Button_ProbeSpacing->setVisible(false);
        Button_FspCorrectionFactor = new QPushButton(pageSample);
        Button_FspCorrectionFactor->setObjectName(QStringLiteral("Button_FspCorrectionFactor"));
        Button_FspCorrectionFactor->setGeometry(QRect(0, 16, 10, 10));
        Button_FspCorrectionFactor->setVisible(false);
        Button_ab = new QPushButton(pageSample);
        Button_ab->setObjectName(QStringLiteral("Button_ab"));
        Button_ab->setGeometry(QRect(0, 20, 10, 10));
        Button_ab->setVisible(false);
        Button_CurrErrorBound = new QPushButton(pageSample);
        Button_CurrErrorBound->setObjectName(QStringLiteral("Button_CurrErrorBound"));
        Button_CurrErrorBound->setGeometry(QRect(0, 24, 10, 10));
        Button_CurrErrorBound->setVisible(false);
        stackedWidgetMain->addWidget(pageSample);
        pageResult = new QWidget();
        pageResult->setObjectName(QStringLiteral("pageResult"));
        pageResult->setGeometry(QRect(0, 0, 1160, 580));
        grpForwardData = new QGroupBox(pageResult);
        grpForwardData->setObjectName(QStringLiteral("grpForwardData"));
        grpForwardData->setGeometry(QRect(20, 10, 1120, 145));
        TableWidget_f = new QTableWidget(grpForwardData);
        TableWidget_f->setObjectName(QStringLiteral("TableWidget_f"));
        TableWidget_f->setGeometry(QRect(20, 30, 1080, 95));
        grpReverseData = new QGroupBox(pageResult);
        grpReverseData->setObjectName(QStringLiteral("grpReverseData"));
        grpReverseData->setGeometry(QRect(20, 165, 1120, 145));
        TableWidget_r = new QTableWidget(grpReverseData);
        TableWidget_r->setObjectName(QStringLiteral("TableWidget_r"));
        TableWidget_r->setGeometry(QRect(20, 30, 1080, 95));
        grpStatistics = new QGroupBox(pageResult);
        grpStatistics->setObjectName(QStringLiteral("grpStatistics"));
        grpStatistics->setGeometry(QRect(20, 330, 540, 145));
        lblAverageTitle = new QLabel(grpStatistics);
        lblAverageTitle->setObjectName(QStringLiteral("lblAverageTitle"));
        lblAverageTitle->setGeometry(QRect(35, 35, 120, 28));
        lblAverageValue = new QLabel(grpStatistics);
        lblAverageValue->setObjectName(QStringLiteral("lblAverageValue"));
        lblAverageValue->setGeometry(QRect(185, 35, 300, 28));
        lblStdTitle = new QLabel(grpStatistics);
        lblStdTitle->setObjectName(QStringLiteral("lblStdTitle"));
        lblStdTitle->setGeometry(QRect(35, 70, 120, 28));
        lblStdValue = new QLabel(grpStatistics);
        lblStdValue->setObjectName(QStringLiteral("lblStdValue"));
        lblStdValue->setGeometry(QRect(185, 70, 300, 28));
        lblFinalResistivityTitle = new QLabel(grpStatistics);
        lblFinalResistivityTitle->setObjectName(QStringLiteral("lblFinalResistivityTitle"));
        lblFinalResistivityTitle->setGeometry(QRect(35, 105, 120, 28));
        lblFinalResistivity = new QLabel(grpStatistics);
        lblFinalResistivity->setObjectName(QStringLiteral("lblFinalResistivity"));
        lblFinalResistivity->setGeometry(QRect(185, 105, 300, 28));
        grpFileInfo = new QGroupBox(pageResult);
        grpFileInfo->setObjectName(QStringLiteral("grpFileInfo"));
        grpFileInfo->setGeometry(QRect(580, 330, 560, 145));
        lblMeasureStartTimeTitle = new QLabel(grpFileInfo);
        lblMeasureStartTimeTitle->setObjectName(QStringLiteral("lblMeasureStartTimeTitle"));
        lblMeasureStartTimeTitle->setGeometry(QRect(35, 35, 120, 28));
        lblMeasureStartTime = new QLabel(grpFileInfo);
        lblMeasureStartTime->setObjectName(QStringLiteral("lblMeasureStartTime"));
        lblMeasureStartTime->setGeometry(QRect(185, 35, 320, 28));
        lblDataPathTitle = new QLabel(grpFileInfo);
        lblDataPathTitle->setObjectName(QStringLiteral("lblDataPathTitle"));
        lblDataPathTitle->setGeometry(QRect(35, 70, 120, 28));
        lblDataSavePath = new QLabel(grpFileInfo);
        lblDataSavePath->setObjectName(QStringLiteral("lblDataSavePath"));
        lblDataSavePath->setGeometry(QRect(185, 70, 340, 42));
        lblDataSavePath->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        btnOpenDataFolder = new QPushButton(grpFileInfo);
        btnOpenDataFolder->setObjectName(QStringLiteral("btnOpenDataFolder"));
        btnOpenDataFolder->setGeometry(QRect(35, 112, 150, 28));
        grpResultActions = new QGroupBox(pageResult);
        grpResultActions->setObjectName(QStringLiteral("grpResultActions"));
        grpResultActions->setGeometry(QRect(20, 490, 1120, 70));
        btnExportCsv = new QPushButton(grpResultActions);
        btnExportCsv->setObjectName(QStringLiteral("btnExportCsv"));
        btnExportCsv->setGeometry(QRect(30, 28, 120, 30));
        btnExportExcel = new QPushButton(grpResultActions);
        btnExportExcel->setObjectName(QStringLiteral("btnExportExcel"));
        btnExportExcel->setGeometry(QRect(170, 28, 120, 30));
        btnCopyFinalResult = new QPushButton(grpResultActions);
        btnCopyFinalResult->setObjectName(QStringLiteral("btnCopyFinalResult"));
        btnCopyFinalResult->setGeometry(QRect(310, 28, 140, 30));
        btnClearResult = new QPushButton(grpResultActions);
        btnClearResult->setObjectName(QStringLiteral("btnClearResult"));
        btnClearResult->setGeometry(QRect(470, 28, 120, 30));
        stackedWidgetMain->addWidget(pageResult);
        pageDebug = new QWidget();
        pageDebug->setObjectName(QStringLiteral("pageDebug"));
        pageDebug->setGeometry(QRect(0, 0, 1160, 580));
        grpPidDebug = new QGroupBox(pageDebug);
        grpPidDebug->setObjectName(QStringLiteral("grpPidDebug"));
        grpPidDebug->setGeometry(QRect(20, 10, 350, 220));
        Label_Name_Kp = new QLabel(grpPidDebug);
        Label_Name_Kp->setObjectName(QStringLiteral("Label_Name_Kp"));
        Label_Name_Kp->setGeometry(QRect(25, 40, 60, 28));
        cin_Kp = new QLineEdit(grpPidDebug);
        cin_Kp->setObjectName(QStringLiteral("cin_Kp"));
        cin_Kp->setGeometry(QRect(95, 40, 120, 30));
        Label_Name_Ti = new QLabel(grpPidDebug);
        Label_Name_Ti->setObjectName(QStringLiteral("Label_Name_Ti"));
        Label_Name_Ti->setGeometry(QRect(25, 80, 60, 28));
        cin_Ti = new QLineEdit(grpPidDebug);
        cin_Ti->setObjectName(QStringLiteral("cin_Ti"));
        cin_Ti->setGeometry(QRect(95, 80, 120, 30));
        Label_Name_Td = new QLabel(grpPidDebug);
        Label_Name_Td->setObjectName(QStringLiteral("Label_Name_Td"));
        Label_Name_Td->setGeometry(QRect(25, 120, 60, 28));
        cin_Td = new QLineEdit(grpPidDebug);
        cin_Td->setObjectName(QStringLiteral("cin_Td"));
        cin_Td->setGeometry(QRect(95, 120, 120, 30));
        ToolButton_ControlAlgo = new QToolButton(grpPidDebug);
        ToolButton_ControlAlgo->setObjectName(QStringLiteral("ToolButton_ControlAlgo"));
        ToolButton_ControlAlgo->setGeometry(QRect(25, 170, 180, 34));
        grpVoltageDebug = new QGroupBox(pageDebug);
        grpVoltageDebug->setObjectName(QStringLiteral("grpVoltageDebug"));
        grpVoltageDebug->setGeometry(QRect(405, 10, 350, 220));
        lblControlVoltageDebugTitle = new QLabel(grpVoltageDebug);
        lblControlVoltageDebugTitle->setObjectName(QStringLiteral("lblControlVoltageDebugTitle"));
        lblControlVoltageDebugTitle->setGeometry(QRect(25, 45, 90, 28));
        cin_ControlVoltage = new QLineEdit(grpVoltageDebug);
        cin_ControlVoltage->setObjectName(QStringLiteral("cin_ControlVoltage"));
        cin_ControlVoltage->setGeometry(QRect(125, 45, 120, 30));
        Button_SendControlVoltage = new QPushButton(grpVoltageDebug);
        Button_SendControlVoltage->setObjectName(QStringLiteral("Button_SendControlVoltage"));
        Button_SendControlVoltage->setGeometry(QRect(25, 95, 150, 36));
        Button_ControlVoltage = new QPushButton(grpVoltageDebug);
        Button_ControlVoltage->setObjectName(QStringLiteral("Button_ControlVoltage"));
        Button_ControlVoltage->setGeometry(QRect(25, 145, 200, 36));
        grpManualCommand = new QGroupBox(pageDebug);
        grpManualCommand->setObjectName(QStringLiteral("grpManualCommand"));
        grpManualCommand->setGeometry(QRect(790, 10, 350, 220));
        Button_SendCurrentPosition = new QPushButton(grpManualCommand);
        Button_SendCurrentPosition->setObjectName(QStringLiteral("Button_SendCurrentPosition"));
        Button_SendCurrentPosition->setGeometry(QRect(25, 45, 180, 36));
        Button_SendVoltageRange = new QPushButton(grpManualCommand);
        Button_SendVoltageRange->setObjectName(QStringLiteral("Button_SendVoltageRange"));
        Button_SendVoltageRange->setGeometry(QRect(25, 95, 180, 36));
        pushButton_3 = new QPushButton(grpManualCommand);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(25, 145, 180, 36));
        grpCurrentReadDebug = new QGroupBox(pageDebug);
        grpCurrentReadDebug->setObjectName(QStringLiteral("grpCurrentReadDebug"));
        grpCurrentReadDebug->setGeometry(QRect(20, 250, 350, 170));
        pushButton = new QPushButton(grpCurrentReadDebug);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(25, 40, 180, 36));
        pushButton_2 = new QPushButton(grpCurrentReadDebug);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(25, 90, 180, 36));
        Label_Name_Current = new QLabel(grpCurrentReadDebug);
        Label_Name_Current->setObjectName(QStringLiteral("Label_Name_Current"));
        Label_Name_Current->setGeometry(QRect(25, 130, 80, 28));
        Label_Current = new QLabel(grpCurrentReadDebug);
        Label_Current->setObjectName(QStringLiteral("Label_Current"));
        Label_Current->setGeometry(QRect(115, 130, 150, 28));
        grpPidState = new QGroupBox(pageDebug);
        grpPidState->setObjectName(QStringLiteral("grpPidState"));
        grpPidState->setGeometry(QRect(405, 250, 350, 170));
        lblPidSpTitle = new QLabel(grpPidState);
        lblPidSpTitle->setObjectName(QStringLiteral("lblPidSpTitle"));
        lblPidSpTitle->setGeometry(QRect(25, 40, 45, 26));
        lblPidSp = new QLabel(grpPidState);
        lblPidSp->setObjectName(QStringLiteral("lblPidSp"));
        lblPidSp->setGeometry(QRect(75, 40, 80, 26));
        lblPidPvTitle = new QLabel(grpPidState);
        lblPidPvTitle->setObjectName(QStringLiteral("lblPidPvTitle"));
        lblPidPvTitle->setGeometry(QRect(25, 70, 45, 26));
        lblPidPv = new QLabel(grpPidState);
        lblPidPv->setObjectName(QStringLiteral("lblPidPv"));
        lblPidPv->setGeometry(QRect(75, 70, 80, 26));
        lblPidErrTitle = new QLabel(grpPidState);
        lblPidErrTitle->setObjectName(QStringLiteral("lblPidErrTitle"));
        lblPidErrTitle->setGeometry(QRect(25, 100, 45, 26));
        lblPidErr = new QLabel(grpPidState);
        lblPidErr->setObjectName(QStringLiteral("lblPidErr"));
        lblPidErr->setGeometry(QRect(75, 100, 80, 26));
        lblPidUkTitle = new QLabel(grpPidState);
        lblPidUkTitle->setObjectName(QStringLiteral("lblPidUkTitle"));
        lblPidUkTitle->setGeometry(QRect(165, 40, 55, 26));
        lblPidUk = new QLabel(grpPidState);
        lblPidUk->setObjectName(QStringLiteral("lblPidUk"));
        lblPidUk->setGeometry(QRect(225, 40, 80, 26));
        lblPidLastUkTitle = new QLabel(grpPidState);
        lblPidLastUkTitle->setObjectName(QStringLiteral("lblPidLastUkTitle"));
        lblPidLastUkTitle->setGeometry(QRect(165, 70, 55, 26));
        lblPidLastUk = new QLabel(grpPidState);
        lblPidLastUk->setObjectName(QStringLiteral("lblPidLastUk"));
        lblPidLastUk->setGeometry(QRect(225, 70, 80, 26));
        Label_Name_Current_2 = new QLabel(grpPidState);
        Label_Name_Current_2->setObjectName(QStringLiteral("Label_Name_Current_2"));
        Label_Name_Current_2->setGeometry(QRect(165, 100, 70, 26));
        Label_RE_Current = new QLabel(grpPidState);
        Label_RE_Current->setObjectName(QStringLiteral("Label_RE_Current"));
        Label_RE_Current->setGeometry(QRect(235, 100, 70, 26));
        grpCommDebug = new QGroupBox(pageDebug);
        grpCommDebug->setObjectName(QStringLiteral("grpCommDebug"));
        grpCommDebug->setGeometry(QRect(790, 250, 350, 310));
        logText_1 = new QTextEdit(grpCommDebug);
        logText_1->setObjectName(QStringLiteral("logText_1"));
        logText_1->setGeometry(QRect(20, 30, 310, 170));
        Button_logText1_CLR = new QPushButton(grpCommDebug);
        Button_logText1_CLR->setObjectName(QStringLiteral("Button_logText1_CLR"));
        Button_logText1_CLR->setGeometry(QRect(20, 210, 90, 30));
        lblAckNackTitle = new QLabel(grpCommDebug);
        lblAckNackTitle->setObjectName(QStringLiteral("lblAckNackTitle"));
        lblAckNackTitle->setGeometry(QRect(20, 248, 90, 26));
        lblAckNack = new QLabel(grpCommDebug);
        lblAckNack->setObjectName(QStringLiteral("lblAckNack"));
        lblAckNack->setGeometry(QRect(120, 248, 160, 26));
        lblOperationDoneTitle = new QLabel(grpCommDebug);
        lblOperationDoneTitle->setObjectName(QStringLiteral("lblOperationDoneTitle"));
        lblOperationDoneTitle->setGeometry(QRect(20, 278, 110, 26));
        lblOperationDone = new QLabel(grpCommDebug);
        lblOperationDone->setObjectName(QStringLiteral("lblOperationDone"));
        lblOperationDone->setGeometry(QRect(135, 278, 160, 26));
        stackedWidgetMain->addWidget(pageDebug);

        retranslateUi(Widget);

        stackedWidgetMain->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QApplication::translate("Widget", "\345\233\233\346\216\242\351\222\210\346\231\266\345\234\206\347\224\265\351\230\273\347\216\207\346\265\213\351\207\217\347\263\273\347\273\237", Q_NULLPTR));
        lblComPort->setText(QApplication::translate("Widget", "COM\345\217\243", Q_NULLPTR));
        Button_SelCOM->setText(QApplication::translate("Widget", "COM", Q_NULLPTR));
        lblConnectStatusTitle->setText(QApplication::translate("Widget", "\350\277\236\346\216\245\347\212\266\346\200\201", Q_NULLPTR));
        lblConnectStatus->setText(QApplication::translate("Widget", "\346\234\252\350\277\236\346\216\245", Q_NULLPTR));
        lblCurrentRangeTitle->setText(QApplication::translate("Widget", "\347\224\265\346\265\201\346\241\243\344\275\215", Q_NULLPTR));
        lblCurrentRange->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblVoltageRangeTitle->setText(QApplication::translate("Widget", "\347\224\265\345\216\213\346\241\243\344\275\215", Q_NULLPTR));
        lblVoltageRange->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblMeasureModeTitle->setText(QApplication::translate("Widget", "\346\265\213\351\207\217\346\250\241\345\274\217", Q_NULLPTR));
        lblMeasureMode->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblMeasureStateTitle->setText(QApplication::translate("Widget", "\346\265\213\351\207\217\347\212\266\346\200\201", Q_NULLPTR));
        lblMeasureState->setText(QApplication::translate("Widget", "\347\251\272\351\227\262", Q_NULLPTR));
        lblNavTitle->setText(QApplication::translate("Widget", "\345\212\237\350\203\275\345\257\274\350\210\252", Q_NULLPTR));
        btnPageExperiment->setText(QApplication::translate("Widget", "\345\256\236\351\252\214\346\265\213\351\207\217", Q_NULLPTR));
        btnPageSample->setText(QApplication::translate("Widget", "\346\240\267\345\223\201\345\217\202\346\225\260", Q_NULLPTR));
        btnPageResult->setText(QApplication::translate("Widget", "\346\225\260\346\215\256\347\273\223\346\236\234", Q_NULLPTR));
        btnPageDebug->setText(QApplication::translate("Widget", "\350\260\203\350\257\225\351\241\265\351\235\242", Q_NULLPTR));
        grpExperimentControl->setTitle(QApplication::translate("Widget", "\345\256\236\351\252\214\346\216\247\345\210\266", Q_NULLPTR));
        lblModeSelect->setText(QApplication::translate("Widget", "\346\265\213\351\207\217\346\250\241\345\274\217", Q_NULLPTR));
        ToolButton_MeasureMode->setText(QApplication::translate("Widget", "\345\215\225\346\254\241\346\265\213\351\207\217", Q_NULLPTR));
        lblCurrentRangeSelect->setText(QApplication::translate("Widget", "\347\224\265\346\265\201\346\241\243\344\275\215", Q_NULLPTR));
        Button_CurrPos->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblVoltageRangeSelect->setText(QApplication::translate("Widget", "\347\224\265\345\216\213\346\241\243\344\275\215", Q_NULLPTR));
        Button_VolRange->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        Button_MeasStart->setText(QApplication::translate("Widget", "\345\274\200\345\247\213\346\265\213\351\207\217", Q_NULLPTR));
        btnStopMeasure->setText(QApplication::translate("Widget", "\345\201\234\346\255\242/\344\270\255\346\255\242", Q_NULLPTR));
        btnClearCurrentData->setText(QApplication::translate("Widget", "\346\270\205\347\251\272\345\275\223\345\211\215\346\225\260\346\215\256", Q_NULLPTR));
        grpRealtimeData->setTitle(QApplication::translate("Widget", "\345\256\236\346\227\266\346\225\260\346\215\256", Q_NULLPTR));
        Label_NameDataVoltage->setText(QApplication::translate("Widget", "\347\224\265\345\216\213", Q_NULLPTR));
        Label_VoltData->setText(QApplication::translate("Widget", "-- V", Q_NULLPTR));
        Label_NameDataCurrent->setText(QApplication::translate("Widget", "\347\224\265\346\265\201", Q_NULLPTR));
        Label_CurrData->setText(QApplication::translate("Widget", "-- A", Q_NULLPTR));
        lblResistanceTitle->setText(QApplication::translate("Widget", "\347\224\265\351\230\273", Q_NULLPTR));
        lblRealtimeResistance->setText(QApplication::translate("Widget", "-- \316\251", Q_NULLPTR));
        Label_NameDataResistivity->setText(QApplication::translate("Widget", "\347\224\265\351\230\273\347\216\207", Q_NULLPTR));
        Label_ResData->setText(QApplication::translate("Widget", "-- \316\251\302\267cm", Q_NULLPTR));
        grpMeasureProgress->setTitle(QApplication::translate("Widget", "\346\265\213\351\207\217\350\277\233\345\272\246", Q_NULLPTR));
        lblStageTitle->setText(QApplication::translate("Widget", "\345\275\223\345\211\215\351\230\266\346\256\265", Q_NULLPTR));
        Label_MeasureProgress->setText(QApplication::translate("Widget", "\347\251\272\351\227\262", Q_NULLPTR));
        lblStageHint->setText(QApplication::translate("Widget", "\346\265\213\351\207\217\350\277\207\347\250\213\347\212\266\346\200\201\344\274\232\345\234\250\346\255\244\345\220\214\346\255\245\346\230\276\347\244\272", Q_NULLPTR));
        grpSampleBasic->setTitle(QApplication::translate("Widget", "\346\240\267\345\223\201\345\217\202\346\225\260", Q_NULLPTR));
        Label_Name_SemiType->setText(QApplication::translate("Widget", "\345\215\212\345\257\274\344\275\223\347\261\273\345\236\213", Q_NULLPTR));
        Button_SelSemiType->setText(QApplication::translate("Widget", "P", Q_NULLPTR));
        Label_Name_Temperature->setText(QApplication::translate("Widget", "\346\270\251\345\272\246", Q_NULLPTR));
        cin_Temperature->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245\346\270\251\345\272\246", Q_NULLPTR));
        Label_Name_Temperature_2->setText(QApplication::translate("Widget", "\342\204\203", Q_NULLPTR));
        Label_Name_SampleThickness->setText(QApplication::translate("Widget", "\346\240\267\345\223\201\345\216\232\345\272\246", Q_NULLPTR));
        cin_Thickness->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245\345\216\232\345\272\246", Q_NULLPTR));
        Label_Name_SampleThickness_2->setText(QApplication::translate("Widget", "mm", Q_NULLPTR));
        Label_Name_SampleDiameter->setText(QApplication::translate("Widget", "\346\240\267\345\223\201\347\233\264\345\276\204", Q_NULLPTR));
        cin_SampleDiameter->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245\346\240\267\345\223\201\347\233\264\345\276\204", Q_NULLPTR));
        Label_Name_SampleDiameter_2->setText(QApplication::translate("Widget", "mm", Q_NULLPTR));
        Label_Name_SampleDiameter_3->setText(QApplication::translate("Widget", "\346\216\242\351\222\210\351\227\264\350\267\235", Q_NULLPTR));
        cin_ProbeSpacing->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245\346\216\242\351\222\210\351\227\264\350\267\235", Q_NULLPTR));
        Label_Name_SampleDiameter_4->setText(QApplication::translate("Widget", "mm", Q_NULLPTR));
        Label_Name_FspCorrectionFactor->setText(QApplication::translate("Widget", "\344\277\256\346\255\243\347\263\273\346\225\260", Q_NULLPTR));
        cin_FspCorrectionFactor->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245\344\277\256\346\255\243\347\263\273\346\225\260", Q_NULLPTR));
        Label_Name_Temperature_3->setText(QApplication::translate("Widget", "a \345\217\202\346\225\260", Q_NULLPTR));
        cin_a->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245a", Q_NULLPTR));
        Label_Name_Temperature_4->setText(QApplication::translate("Widget", "b \345\217\202\346\225\260", Q_NULLPTR));
        cin_b->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245b", Q_NULLPTR));
        grpCorrectionFactor->setTitle(QApplication::translate("Widget", "\344\277\256\346\255\243\345\233\240\345\255\220", Q_NULLPTR));
        lblWsTitle->setText(QApplication::translate("Widget", "WS", Q_NULLPTR));
        lblWS->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblSdTitle->setText(QApplication::translate("Widget", "SD", Q_NULLPTR));
        lblSD->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblGeometryFactorTitle->setText(QApplication::translate("Widget", "\345\207\240\344\275\225\344\277\256\346\255\243", Q_NULLPTR));
        lblGeometryFactor->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblTemperatureFactorTitle->setText(QApplication::translate("Widget", "\346\270\251\345\272\246\344\277\256\346\255\243", Q_NULLPTR));
        lblTemperatureFactor->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblTotalFactorTitle->setText(QApplication::translate("Widget", "\347\273\274\345\220\210\347\263\273\346\225\260", Q_NULLPTR));
        lblTotalFactor->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        grpSampleActions->setTitle(QApplication::translate("Widget", "\345\217\202\346\225\260\350\256\276\347\275\256", Q_NULLPTR));
        Label_Name_SampleDiameter_5->setText(QApplication::translate("Widget", "\347\224\265\346\265\201\350\257\257\345\267\256\350\214\203\345\233\264", Q_NULLPTR));
        cin_CurrErrorBound->setPlaceholderText(QApplication::translate("Widget", "\350\276\223\345\205\245\350\214\203\345\233\264", Q_NULLPTR));
        Label_Name_SampleDiameter_6->setText(QApplication::translate("Widget", "%", Q_NULLPTR));
        btnSaveParams->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\345\217\202\346\225\260", Q_NULLPTR));
        btnResetParams->setText(QApplication::translate("Widget", "\346\201\242\345\244\215\351\273\230\350\256\244", Q_NULLPTR));
        btnImportParams->setText(QApplication::translate("Widget", "\345\257\274\345\205\245\345\217\202\346\225\260", Q_NULLPTR));
        btnExportParams->setText(QApplication::translate("Widget", "\345\257\274\345\207\272\345\217\202\346\225\260", Q_NULLPTR));
        Button_Temperature->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\346\270\251\345\272\246", Q_NULLPTR));
        Button_Thickness->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\345\216\232\345\272\246", Q_NULLPTR));
        Button_SampleDiameter->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\347\233\264\345\276\204", Q_NULLPTR));
        Button_ProbeSpacing->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\351\227\264\350\267\235", Q_NULLPTR));
        Button_FspCorrectionFactor->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\344\277\256\346\255\243\347\263\273\346\225\260", Q_NULLPTR));
        Button_ab->setText(QApplication::translate("Widget", "\344\277\235\345\255\230ab", Q_NULLPTR));
        Button_CurrErrorBound->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\350\257\257\345\267\256\350\214\203\345\233\264", Q_NULLPTR));
        grpForwardData->setTitle(QApplication::translate("Widget", "\346\255\243\345\220\221\346\265\213\351\207\217\346\225\260\346\215\256", Q_NULLPTR));
        grpReverseData->setTitle(QApplication::translate("Widget", "\345\217\215\345\220\221\346\265\213\351\207\217\346\225\260\346\215\256", Q_NULLPTR));
        grpStatistics->setTitle(QApplication::translate("Widget", "\347\273\237\350\256\241\347\273\223\346\236\234", Q_NULLPTR));
        lblAverageTitle->setText(QApplication::translate("Widget", "\345\271\263\345\235\207\347\224\265\351\230\273\347\216\207", Q_NULLPTR));
        lblAverageValue->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblStdTitle->setText(QApplication::translate("Widget", "\346\240\207\345\207\206\345\267\256", Q_NULLPTR));
        lblStdValue->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblFinalResistivityTitle->setText(QApplication::translate("Widget", "\346\234\200\347\273\210\347\224\265\351\230\273\347\216\207", Q_NULLPTR));
        lblFinalResistivity->setText(QApplication::translate("Widget", "-- \316\251\302\267cm", Q_NULLPTR));
        grpFileInfo->setTitle(QApplication::translate("Widget", "\346\226\207\344\273\266\344\277\241\346\201\257", Q_NULLPTR));
        lblMeasureStartTimeTitle->setText(QApplication::translate("Widget", "\346\265\213\351\207\217\345\274\200\345\247\213\346\227\266\351\227\264", Q_NULLPTR));
        lblMeasureStartTime->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblDataPathTitle->setText(QApplication::translate("Widget", "\346\225\260\346\215\256\344\277\235\345\255\230\350\267\257\345\276\204", Q_NULLPTR));
        lblDataSavePath->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        btnOpenDataFolder->setText(QApplication::translate("Widget", "\346\211\223\345\274\200\346\225\260\346\215\256\346\226\207\344\273\266\345\244\271", Q_NULLPTR));
        grpResultActions->setTitle(QApplication::translate("Widget", "\347\273\223\346\236\234\346\223\215\344\275\234", Q_NULLPTR));
        btnExportCsv->setText(QApplication::translate("Widget", "\345\257\274\345\207\272 CSV", Q_NULLPTR));
        btnExportExcel->setText(QApplication::translate("Widget", "\345\257\274\345\207\272 Excel", Q_NULLPTR));
        btnCopyFinalResult->setText(QApplication::translate("Widget", "\345\244\215\345\210\266\346\234\200\347\273\210\347\273\223\346\236\234", Q_NULLPTR));
        btnClearResult->setText(QApplication::translate("Widget", "\346\270\205\347\251\272\347\273\223\346\236\234", Q_NULLPTR));
        grpPidDebug->setTitle(QApplication::translate("Widget", "PID \345\217\202\346\225\260", Q_NULLPTR));
        Label_Name_Kp->setText(QApplication::translate("Widget", "Kp", Q_NULLPTR));
        cin_Kp->setPlaceholderText(QApplication::translate("Widget", "Kp", Q_NULLPTR));
        Label_Name_Ti->setText(QApplication::translate("Widget", "Ti", Q_NULLPTR));
        cin_Ti->setPlaceholderText(QApplication::translate("Widget", "Ti", Q_NULLPTR));
        Label_Name_Td->setText(QApplication::translate("Widget", "Td", Q_NULLPTR));
        cin_Td->setPlaceholderText(QApplication::translate("Widget", "Td", Q_NULLPTR));
        ToolButton_ControlAlgo->setText(QApplication::translate("Widget", "PID\347\256\227\346\263\225:\345\205\263\351\227\255", Q_NULLPTR));
        grpVoltageDebug->setTitle(QApplication::translate("Widget", "\345\216\213\346\216\247\347\224\265\345\216\213\350\260\203\350\257\225", Q_NULLPTR));
        lblControlVoltageDebugTitle->setText(QApplication::translate("Widget", "\346\216\247\345\210\266\347\224\265\345\216\213", Q_NULLPTR));
        cin_ControlVoltage->setPlaceholderText(QApplication::translate("Widget", "0~3V", Q_NULLPTR));
        Button_SendControlVoltage->setText(QApplication::translate("Widget", "\345\217\221\351\200\201\346\216\247\345\210\266\347\224\265\345\216\213", Q_NULLPTR));
        Button_ControlVoltage->setText(QApplication::translate("Widget", "\344\277\235\345\255\230\345\275\223\345\211\215\346\241\243\344\275\215\345\216\213\346\216\247", Q_NULLPTR));
        grpManualCommand->setTitle(QApplication::translate("Widget", "\346\211\213\345\212\250\345\221\275\344\273\244", Q_NULLPTR));
        Button_SendCurrentPosition->setText(QApplication::translate("Widget", "\345\217\221\351\200\201\347\224\265\346\265\201\346\241\243\344\275\215", Q_NULLPTR));
        Button_SendVoltageRange->setText(QApplication::translate("Widget", "\345\217\221\351\200\201\347\224\265\345\216\213\346\241\243\344\275\215", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("Widget", "\346\270\205\347\220\206\346\265\213\351\207\217\347\274\223\345\255\230", Q_NULLPTR));
        grpCurrentReadDebug->setTitle(QApplication::translate("Widget", "\347\224\265\346\265\201\350\257\273\345\217\226\350\260\203\350\257\225", Q_NULLPTR));
        pushButton->setText(QApplication::translate("Widget", "\345\274\200\345\247\213\346\265\213\347\224\265\346\265\201", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("Widget", "\345\201\234\346\255\242\346\265\213\347\224\265\346\265\201", Q_NULLPTR));
        Label_Name_Current->setText(QApplication::translate("Widget", "\345\275\223\345\211\215\347\224\265\346\265\201", Q_NULLPTR));
        Label_Current->setText(QApplication::translate("Widget", "-- A", Q_NULLPTR));
        grpPidState->setTitle(QApplication::translate("Widget", "PID \347\212\266\346\200\201", Q_NULLPTR));
        lblPidSpTitle->setText(QApplication::translate("Widget", "SP", Q_NULLPTR));
        lblPidSp->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblPidPvTitle->setText(QApplication::translate("Widget", "PV", Q_NULLPTR));
        lblPidPv->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblPidErrTitle->setText(QApplication::translate("Widget", "Err", Q_NULLPTR));
        lblPidErr->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblPidUkTitle->setText(QApplication::translate("Widget", "uk", Q_NULLPTR));
        lblPidUk->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblPidLastUkTitle->setText(QApplication::translate("Widget", "Last uk", Q_NULLPTR));
        lblPidLastUk->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        Label_Name_Current_2->setText(QApplication::translate("Widget", "\345\256\236\346\265\213\347\224\265\346\265\201", Q_NULLPTR));
        Label_RE_Current->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        grpCommDebug->setTitle(QApplication::translate("Widget", "\351\200\232\344\277\241\350\260\203\350\257\225", Q_NULLPTR));
        Button_logText1_CLR->setText(QApplication::translate("Widget", "\346\270\205\347\251\272", Q_NULLPTR));
        lblAckNackTitle->setText(QApplication::translate("Widget", "ACK/NACK", Q_NULLPTR));
        lblAckNack->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
        lblOperationDoneTitle->setText(QApplication::translate("Widget", "Operation Done", Q_NULLPTR));
        lblOperationDone->setText(QApplication::translate("Widget", "--", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
